name: Output Information
on: workflow_dispatch
jobs: 
    info:
        runs-on: ubuntu-latest
        steps: 
            - name: Output Github Cotext
              run: echo "${{ toJSON(github) }}"
